---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: postfacto
spec:
  title: App Name
  icon: https://raw.githubusercontent.com/cncf/artwork/master/projects/kubernetes/icon/color/kubernetes-icon-color.png
  statusInformers:
    - deployment/postfacto
  ports:
    - serviceName: "postfacto"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://postfacto"
