---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: postfacto
spec:
  groups:
  - name: postfacto
    title: Postfacto Configuration
    description: Configures the Postfacto application
    items:
    - name: fqdn
      title: Host
      help_text: "The fully qualifed domain name for the postfacto instance"
      type: text
      recommended: true
      default: "postfacto.local"
    - name: google_oath_client_id
      title: Google Client ID
      help_text: "The Google oAuth client ID to use to allow users to log in using a google account"	
      type: text
      default: ""
      recommended: true
    - name: disable_ssl_redirect
      title: Disable SSL Redirect
      help_text: "By default Postfacto redirects to HTTPS by default, setting this to true disables that behaviour and can be useful when getting started"
      type: bool
      value: false
    - name: secret_key_base
      title: Secret Key Base
      help_text: "Used for signing and encryption, should be set to a random value. Required to perserve sessions across upgrades"
      type: password
      default: repl{{ RandomString 10 }}
      when: false
  - name: datastores
    title: Data Service Configuration
    description: Configurations the datastores for Postfacto 
    items:
    - name: postgres_type
      type: select_one
      title: Postgres
      default: embedded_postgres
      items:
        - name: embedded_postgres
          title: Embedded Postgres
        - name: external_postgres_inline
          title: External Postgres
    - name: embedded_postgres_password
      title: Postgres Password
      help_text: "Password for the embedded postgres database"	
      type: password
      value: repl{{ RandomString 32 }}
    - name: external_postgres_host
      title: Postgres Host
      when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
      type: text
      default: postgres
    - name: external_postgres_port
      title: Postgres Port
      when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
      type: text
      default: "5432"
    - name: external_postgres_user
      title: Postgres Username
      when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
      type: text
      required: true
    - name: external_postgres_password
      title: Postgres Password
      when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
      type: password
      required: true
    - name: external_postgres_db
      title: Postgres Database
      when: '{{repl ConfigOptionEquals "postgres_type" "external_postgres_inline"}}'
      type: text
      default: postfacto
    - name: redis_type
      type: select_one
      title: Redis
      default: embedded_redis
      items:
        - name: embedded_redis
          title: Embedded Redis
        - name: external_redis_inline
          title: External Redis
    - name: embedded_redis_password
      title: Redis Password
      help_text: "Password for the embedded redis datatstore"	
      type: password
      value: repl{{ RandomString 32 }}
    - name: external_redis_host
      title: Redis Host
      when: '{{repl ConfigOptionEquals "redis_type" "external_redis_inline"}}'
      type: text
      default: redis
    - name: external_redis_port
      title: Redis Port
      when: '{{repl ConfigOptionEquals "redis_type" "external_redis_inline"}}'
      type: text
      default: "6379"
    - name: external_redis_user
      title: Redis Username
      when: '{{repl ConfigOptionEquals "redis_type" "external_redis_inline"}}'
      type: text
    - name: external_redis_password
      title: Redis Password
      when: '{{repl ConfigOptionEquals "redis_type" "external_redis_inline"}}'
      type: password
      required: true
