---
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: postfacto
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        selector:
          - app=postfacto
          - component=postfacto
        namespace: '{{repl Namespace }}'
        limits:
          maxAge: 30d
          maxLines: 10000
