---
apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: postfacto
spec:
  title: Postfacto
  icon: https://raw.githubusercontent.com/pivotal/postfacto/master/web/src/images/happy.svg
  statusInformers:
    - deployment/postfacto
    - statefulset/postfacto-postgresql
    - statefulset/postfacto-redis-master
    - statefulset/postfacto-redis-replicas
  ports:
    - serviceName: "postfacto"
      servicePort: 80
      localPort: 8888
      applicationUrl: "http://postfacto"
