---
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: postfacto
spec:
  groups:
  - name: postfacto
    title: Postfacto Configuration
    description: Configures the Postfacto application
    items:
    - name: fqdn
      title: Host
      help_text: "The fully qualifed domain name for the postfacto instance"
      type: text
      recommended: true
      default: "postfacto.local"
    - name: google_oath_client_id
      title: Google Client ID
      help_text: "The Google oAuth client ID to use to allow users to log in using a google account"	
      type: text
      default: ""
      recommended: true
    - name: disable_ssl_redirect
      title: Disable SSL Redirect
      help_text: "By default Postfacto redirects to HTTPS by default, setting this to true disables that behaviour and can be useful when getting started"
      type: bool
      value: false
    - name: secret_key_base
      title: Secret Key Base
      help_text: "Used for signing and encryption, should be set to a random value. Required to perserve sessions across upgrades"
      type: password
      value: repl{{ RandomString 10 }}
      when: false
  - name: datastores
    title: Data Service Configuration
    description: Configurations the datastores for Postfacto 
    items:
    - name: embedded_postgres_username
      title: Postgres Username
      help_text: "Username for the embedded postgres database"	
      type: text
      value: postfacto
      when: false
    - name: embedded_postgres_database
      title: Postgres Database
      help_text: "Database name for the embedded postgres database"	
      type: text
      value: postfacto
      when: false
    - name: postgres_secret_type
      type: select_one
      title: Postgres Authentication
      default: specify_password
      items:
        - name: specify_password
          title: Specify Password
        - name: existing_secret
          title: Use Existing Secret
    - name: embedded_postgres_password
      title: Postgres Password
      help_text: "Password for the embedded postgres database"	
      type: password
      value: repl{{ RandomString 32 }}
      when: '{{repl ConfigOptionEquals "postgres_secret_type" "specify_password"}}'
    - name: existing_postgres_secret
      title: Existing Secret 
      type: text    
      when: '{{repl ConfigOptionEquals "postgres_secret_type" "existing_secret"}}'
    - name: redis_secret_type
      type: select_one
      title: Redis Authentication
      default: specify_password
      items:
        - name: specify_password
          title: Specify Password
        - name: existing_secret
          title: Use Existing Secret
    - name: embedded_redis_password
      title: Redis Password
      help_text: "Password for the embedded redis datatstore"	
      type: password
      value: repl{{ RandomString 32 }}
      when: '{{repl ConfigOptionEquals "redis_secret_type" "specify_password"}}'
    - name: existing_redis_secret
      title: Existing Secret 
      type: text
      when: '{{repl ConfigOptionEquals "redis_secret_type" "existing_secret"}}'
