apiVersion: kots.io/v1beta1
kind: HelmChart
metadata:
  name: postfacto

spec:
  chart:
    name: postfacto
    chartVersion: 0.5.0-beta

  # helmVersion identifies the Helm Version used to render the Chart. Default is v2.
  helmVersion: v3

  # useHelmInstall identifies whether this Helm chart will use the
  # Replicated Helm installation (false) or native Helm installation (true). Default is false.
  # Native Helm installations are only available for Helm v3 charts.
  useHelmInstall: false

  values:
    googleOAuthClientId: repl{{ ConfigOption "google_oath_client_id" }}
    disable_ssl_redirect: repl{{ ConfigOption "disable_ssl_redirect" }}
    secret_key_base: repl{{ ConfigOption "secret_key_base" }}

    redis:
      password: repl{{ ConfigOption "redis_password" }}

    postgresql:
      postgresqlPassword: repl{{ ConfigOption "postgres_password" }}

  optionalValues:
    - when: 'repl{{ not ( empty ( ConfigOption "fqdn" )) }}'
      recursiveMerge: true
      values:
        ingress:
          enabled: true
          hosts:
          - host: repl{{ ConfigOption "fqdn" }}

  # When building AirGap, metrics needs to be explicitly enabled so the prometheus image can be bundled along. 
  # Kots does not include the image unless the service is explicitly enabled during the bundle building process.
  builder:
    metrics:
      enabled: true
